package client.presentation.billsui.watcher;

public enum State {
	COURIERSTART, COURIERINPUTINFOR,COURIERMAKEBILL,COURIERSEARCH,
	LOGMAINFRAME,COVER,
	ZHONG_START,ZHONG_ARRIVAL,ZHONG_TRANSFER,ZHONG_ENTRUCKING;
}
